variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

stages:
  - test

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  - python -V
  - pip install -r requirements/doc.txt
  - cd raw2l1

test:
  stage: test
  image: python:$PYTHON_VERSION
  script:
    - py.test --cov
  coverage: '/\d+\%\s*$/'
  allow_failure: true
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10"]

# test_py38:
#   stage: test
#   image: python:3.8
#   script:
#     - py.test
#   allow_failure: true

# test_py39:
#   stage: test
#   image: python:3.9
#   script:
#     - py.test
#   allow_failure: true

# test_py310:
#   stage: test
#   image: python:3.10
#   script:
#     - py.test --cov
#   coverage: '/\d+\%\s*$/'
#   allow_failure: true
