stages:
  - test
  - quality
  - lint
  - doc

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install -r requirements/requirements-dev.txt
  - cd raw2l1

test:
  stage: test
  image: python:$PYTHON_VERSION
  script:
    - py.test --junitxml=report.xml --cov
  coverage: '/\d+\%\s*$/'
  artifacts:
    when: always
    reports:
      junit: raw2l1/report.xml
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10", "3.11"]

ruff:
  stage: quality
  image: python:3.11
  needs: ["test"]
  script:
    - cd ..
    - ruff --format=gitlab raw2l1 > gl-code-quality-report.json
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

black:
  stage: lint
  image: python:3.11
  needs: ["test"]
  script:
    - black --check .
  allow_failure: true

pages:
  stage: doc
  image: python:3.11
  needs: ["test"]
  script:
    - cd ..
    - make html
  artifacts:
    paths:
      - public
  only:
    - master