variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

stages:
  - test

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  - python -V
  - pip install -r requirements.txt
  - cd raw2l1

test_py36:
  stage: test
  image: python:3.6
  script:
    - py.test --cov
  coverage: '/\d+\%\s*$/'

test_py37:
  stage: test
  image: python:3.7
  script:
    - py.test --cov
  coverage: '/\d+\%\s*$/'
  allow_failure: true
