stages:
  - test
  - lint

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install -r requirements/requirements-dev.txt
  - cd raw2l1

test:
  stage: test
  image: python:$PYTHON_VERSION
  script:
    - py.test --junitxml=report.xml --cov
  coverage: '/\d+\%\s*$/'
  artifacts:
    when: always
    reports:
      junit: raw2l1/report.xml
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10", "3.11"]

black:
  stage: lint
  image: python:3.11
  script:
    - black --check raw2l1
  allow_failure: true

ruff:
  stage: lint
  image: python:3.11
  script:
    - ruff --format=gitlab raw2l1
  allow_failure: true