image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  - python -V
  - pip install -r requirements.txt
  - cd raw2l1

test:
  script:
    - py.test --cov
  coverage: '/\d+\%\s*$/'
