[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "raw2l1"
version = "3.2.4"
description = "Convert raw lidar/radiometer files to level-1 NetCDF products"
authors = [{ name = "ACTRIS-CCRES", email = "ccres-dev@listes.ipsl.fr" }]
readme = "README.md"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU Affero General Public License v3',
    'Natural Language :: English',
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]
requires-python = ">=3.10"
dependencies = ["numpy", "netCDF4>=1.6", "gitpython", "xarray"]

[project.scripts]
raw2l1 = "raw2l1.raw2l1:main"

[project.license]
file = "LICENSE"

[project.urls]
homepage = "https://github.com/ACTRIS-CCRES/raw2l1"
repository = "https://github.com/ACTRIS-CCRES/raw2l1"
changelog = "https://github.com/ACTRIS-CCRES/raw2l1/blob/main/CHANGELOG.md"
"Bug Tracker" = "https://github.com/ACTRIS-CCRES/raw2l1/issues"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
raw2l1 = ["conf/*.ini"]

[dependency-groups]
dev = [
    "commitizen>=4.13.10",
    "pre-commit>=4.5.1",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.11",
    "ty>=0.0.32",
]

[tool.commitizen]
version = "3.2.4"
version_files = ["pyproject.toml:version"]
tag_format = "v$version"
changelog_file = "CHANGELOG.md"
update_changelog_on_bump = true
bump_message = "chore: bump version $current_version → $new_version"
pre_bump_hooks = []
post_bump_hooks = []
retry_after_failure = true
