name: raw2l1-dev
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip

  # required dependencies
  - numpy
  - netCDF4>=1.6
  - gitpython

  # test dependencies
  - pytest>=7.0.0
  - pytest-cov
  - pytest-xdist>=2.2.0
  - coverage

  # code checks
  - pre-commit>=2.15.0
  - pyupgrade
  - ruff=0.1.6

  # mypy
  - types-pyyaml

  # documentation
  - gitdb
  - sphinx
  - sphinx-rtd-theme
